name: habi_lite
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  collection: ^1.19.0
  dynamic_color: ^1.7.0
  file_picker: ^8.1.6
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.2
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  intl: any
  path: ^1.9.0
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"